version: '3.8'

services:
  keycloak_osu_stage:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start
      - --hostname-strict=false
      - --hostname-strict-https=false
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=172.18.0.1
      - KC_DB_URL_DATABASE=keycloak-db
      - KC_DB_URL_PORT=5502
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=${KEYCLOAK_POSTGRES_PASSWORD}
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_URL=https://keycloak-stg.aimcup.xyz
      - KC_HOSTNAME_ADMIN_URL=https://keycloak-stg.aimcup.xyz
    ports:
      - 8202:8080
      - 8090:8443
    volumes:
      - ./providers:/opt/keycloak/providers
    container_name: keycloak_stage

networks:
  default:
    external: true
    name: aimcup-network
