version: '3.8'

services:
  keycloak_db_stage:
    image: postgres:latest
    container_name: keycloak_db_stage
    environment:
      POSTGRES_USER: ${STG_KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${STG_KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: keycloak-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$STG_KEYCLOAK_POSTGRES_USER keycloak-db" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5502:5432"

networks:
  default:
    external: true
    name: aimcup-network