version: '3.8'

services:
  keycloak_osu_stage:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start
      - --hostname-strict=false
      - --hostname-strict-https=false
    environment:
      - KEYCLOAK_ADMIN=${STG_KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${STG_KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=${STG_KEYCLOAK_HOST}
      - KC_DB_URL_DATABASE=keycloak-db
      - KC_DB_URL_PORT=${STG_KEYCLOAK_PORT}
      - KC_DB_USERNAME=${STG_KEYCLOAK_POSTGRES_USER}
      - KC_DB_PASSWORD=${STG_KEYCLOAK_POSTGRES_PASSWORD}
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_URL=${STG_KEYCLOAK_HOSTNAME}
      - KC_HOSTNAME_ADMIN_URL=${STG_KEYCLOAK_HOSTNAME}
    ports:
      - 8202:8080
      - 8090:8443
    volumes:
      - ./providers:/opt/keycloak/providers
    container_name: keycloak_stage

networks:
  default:
    external: true
    name: aimcup-network
