version: '3.8'

services:
  keycloak_db_prod:
    image: postgres:latest
    container_name: keycloak_db_prod
    environment:
      POSTGRES_USER: ${PRD_KEYCLOAK_POSTGRES_USER}
      POSTGRES_PASSWORD: ${PRD_KEYCLOAK_POSTGRES_PASSWORD}
      POSTGRES_DB: keycloak-db
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready --dbname=keycloak-db --username=${PRD_KEYCLOAK_POSTGRES_USER}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5402:5432"

networks:
  default:
    external: true
    name: aimcup-network