version: '3.8'

services:
  keycloak_osu_prod:
    image: quay.io/keycloak/keycloak:22.0.5
    command:
      - start
      - --hostname-strict=false
      - --hostname-strict-https=false
    environment:
      - KEYCLOAK_ADMIN=${PRD_KEYCLOAK_ADMIN}
      - KEYCLOAK_ADMIN_PASSWORD=${PRD_KEYCLOAK_PASSWORD}
      - KC_DB=postgres
      - KC_DB_URL_HOST=${PRD_KEYCLOAK_HOST}
      - KC_DB_URL_DATABASE=keycloak-db
      - KC_DB_URL_PORT=${PRD_KEYCLOAK_PORT}
      - KC_DB_USERNAME=${PRD_KEYCLOAK_POSTGRES_USER}
      - KC_DB_PASSWORD=${PRD_KEYCLOAK_POSTGRES_PASSWORD}
      - KC_PROXY=edge
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_URL=${PRD_KEYCLOAK_HOSTNAME}
      - KC_HOSTNAME_ADMIN_URL=${PRD_KEYCLOAK_HOSTNAME}
    ports:
      - 8102:8080
      - 8091:8443
    volumes:
      - ./providers:/opt/keycloak/providers
    networks:
      - keycloak
    container_name: keycloak_stage

networks:
  default:
    external: true
    name: aimcup-network