name: Deploy to Production

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v3
      - name: Run keycloak db (if needed)
        run: |
          docker-compose -f docker/prd/prd-run-database-job.yml up -d --build
        env:
          KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.KEYCLOAK_POSTGRES_PASSWORD }}
          KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
          KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}
      - name: Build and deploy the Docker image
        run: |
          docker-compose -f docker/prd/prd-build-deploy-job.yml up -d --build
        env:
          KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.KEYCLOAK_POSTGRES_PASSWORD }}
          KEYCLOAK_ADMIN: ${{ secrets.KEYCLOAK_ADMIN }}
          KEYCLOAK_PASSWORD: ${{ secrets.KEYCLOAK_PASSWORD }}