name: Deploy to Production

on:
  workflow_dispatch:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v3
      - name: Run keycloak db (if needed)
        run: |
          docker-compose -f docker/prd/prd-run-database-job.yml up -d --build
        env:
          PRD_KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.PRD_KEYCLOAK_POSTGRES_PASSWORD }}
          PRD_KEYCLOAK_ADMIN: ${{ secrets.PRD_KEYCLOAK_ADMIN }}
          PRD_KEYCLOAK_PASSWORD: ${{ secrets.PRD_KEYCLOAK_PASSWORD }}
          PRD_KEYCLOAK_POSTGRES_USER: ${{ secrets.PRD_KEYCLOAK_POSTGRES_USER }}
      - name: Build and deploy the Docker image
        run: |
          mvn clean package
          mkdir -p docker/prd/providers
          cp target/*.jar docker/prd/providers/keycloak-osu-idp.jar
          docker-compose -f docker/prd/prd-build-deploy-job.yml up -d --build
        env:
          PRD_KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.PRD_KEYCLOAK_POSTGRES_PASSWORD }}
          PRD_KEYCLOAK_ADMIN: ${{ secrets.PRD_KEYCLOAK_ADMIN }}
          PRD_KEYCLOAK_PASSWORD: ${{ secrets.PRD_KEYCLOAK_PASSWORD }}
          PRD_KEYCLOAK_POSTGRES_USER: ${{ secrets.PRD_KEYCLOAK_POSTGRES_USER }}
          PRD_KEYCLOAK_HOST: ${{ secrets.PRD_KEYCLOAK_HOST }}
          PRD_KEYCLOAK_HOSTNAME: ${{ secrets.PRD_KEYCLOAK_HOSTNAME }}
          PRD_KEYCLOAK_PORT: ${{ secrets.PRD_KEYCLOAK_PORT }}