name: Deploy to Staging

on:
  pull_request:
    types:
      - closed
    branches:
      - stage
  workflow_dispatch:
    branches: [ "stage" ]

jobs:
  build:
    runs-on:
      group: Default
    steps:
      - uses: actions/checkout@v3
      - name: Run keycloak db (if needed)
        run: |
          docker-compose -f docker/stg/stg-run-database-job.yml up -d --build
        env:
          STG_KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.STG_KEYCLOAK_POSTGRES_PASSWORD }}
          STG_KEYCLOAK_ADMIN: ${{ secrets.STG_KEYCLOAK_ADMIN }}
          STG_KEYCLOAK_PASSWORD: ${{ secrets.STG_KEYCLOAK_PASSWORD }}
          STG_KEYCLOAK_POSTGRES_USER: ${{ secrets.STG_KEYCLOAK_POSTGRES_USER }}
      - name: Build and deploy the Docker image
        run: |
          mvn clean package
          mkdir -p docker/stg/providers
          cp target/*.jar docker/stg/providers/keycloak-osu-idp.jar
          docker-compose -f docker/stg/stg-build-deploy-job.yml up -d --build
        env:
          STG_KEYCLOAK_POSTGRES_PASSWORD: ${{ secrets.STG_KEYCLOAK_POSTGRES_PASSWORD }}
          STG_KEYCLOAK_ADMIN: ${{ secrets.STG_KEYCLOAK_ADMIN }}
          STG_KEYCLOAK_PASSWORD: ${{ secrets.STG_KEYCLOAK_PASSWORD }}
          STG_KEYCLOAK_POSTGRES_USER: ${{ secrets.STG_KEYCLOAK_POSTGRES_USER }}
          STG_KEYCLOAK_HOST: ${{ secrets.STG_KEYCLOAK_HOST }}
          STG_KEYCLOAK_HOSTNAME: ${{ secrets.STG_KEYCLOAK_HOSTNAME }}
          STG_KEYCLOAK_PORT: ${{ secrets.STG_KEYCLOAK_PORT }}